version: "3"
services:
  mysql:
    container_name: mysql
    image: elestio/mysql:${SOFTWARE_VERSION_TAG}
    restart: always
    command: mysqld --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --max_connections=1000 --gtid-mode=ON --enforce-gtid-consistency=ON ${CLUSTER_OPTIONS}
    environment:
      MYSQL_ROOT_PASSWORD: ${SOFTWARE_PASSWORD}
    ports:
      - '3306:3306'
    volumes:
      - ./data:/var/lib/mysql
      - ./sql:/docker-entrypoint-initdb.d

  pma:
    container_name: phpmyadmin
    image: phpmyadmin
    restart: always
    links:
      - mysql:mysql
    ports:
      - "172.17.0.1:24581:80"
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_USER: root
      PMA_PASSWORD: ${SOFTWARE_PASSWORD}
      UPLOAD_LIMIT: 500M
      MYSQL_USERNAME: root
      MYSQL_ROOT_PASSWORD: ${SOFTWARE_PASSWORD}
    depends_on:
      - mysql
